In [2]:
import numpy as np 

In [2]:
l = [1,2,3,4,5,6]

In [3]:
#convert this data into array
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [9]:
l1 = [4,5,6,7,"jaya" , 34.565, True]

In [10]:
#as it is converted each and every element into string
a1 = np.array(l1)

In [8]:
a1

array(['4', '5', '6', '7', 'jaya', '34.565', 'True'], dtype='<U32')

In [11]:
a2 = np.array([[1,2,3] , [4,5,6]])

In [12]:
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9]]])

In [13]:
a1

array(['4', '5', '6', '7', 'jaya', '34.565', 'True'], dtype='<U32')

In [11]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [14]:
a1.ndim

1

In [15]:
a2.ndim

2

In [19]:
a3.ndim

3

In [16]:
a1.size

7

In [21]:
a2.size

6

In [22]:
a3.size

9

In [17]:
a1.shape

(7,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(1, 3, 3)

In [20]:
a1

array(['4', '5', '6', '7', 'jaya', '34.565', 'True'], dtype='<U32')

In [21]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [4]:
np.random.randint(2,50 ,(3,4) )

array([[34, 12,  7,  5],
       [15, 48,  5, 38],
       [ 2, 15, 37,  5]])

In [23]:
#randint will generate only integer values
np.random.randint(2,50,(2,3,4) )

array([[[36, 11, 39, 15],
        [14, 20, 36, 11],
        [ 5, 32, 16, 31]],

       [[35, 46, 11, 11],
        [31, 19, 33, 45],
        [35,  4, 36, 20]]])

In [24]:
np.random.rand(5,4)

array([[0.33718797, 0.1932242 , 0.01665194, 0.55450941],
       [0.35578001, 0.04290613, 0.19676326, 0.78427553],
       [0.15289351, 0.03919554, 0.56441548, 0.36706919],
       [0.61009022, 0.76604352, 0.85466252, 0.37033717],
       [0.561761  , 0.45744802, 0.9574856 , 0.53055336]])

In [5]:
#randn gives standard normal distribution with zero mean and sd=1
a4 =  np.random.randn(4,4)

In [6]:
a4

array([[-0.82700022,  1.14365802, -0.71306881,  0.19742828],
       [-0.18817338, -1.69836077,  0.62796614,  1.79629774],
       [ 0.05368645,  0.0575509 , -2.41344655,  0.21507751],
       [ 0.18133552,  0.4542044 , -0.75350661, -1.40400008]])

In [8]:
#we need to reshape with the same size
a4.reshape(2,8)

array([[-0.82700022,  1.14365802, -0.71306881,  0.19742828, -0.18817338,
        -1.69836077,  0.62796614,  1.79629774],
       [ 0.05368645,  0.0575509 , -2.41344655,  0.21507751,  0.18133552,
         0.4542044 , -0.75350661, -1.40400008]])

In [28]:
a4.reshape(8,2)

array([[ 1.13052507,  0.1219807 ],
       [-0.10991758, -1.63933954],
       [-0.62946391,  1.77990465],
       [ 1.21865348, -1.04202572],
       [ 0.07866904, -0.12919526],
       [-1.12680126, -0.53413491],
       [-0.95898833,  1.20943188],
       [ 1.61016272, -0.01859783]])

In [29]:
a4.reshape(16,1)

array([[ 1.13052507],
       [ 0.1219807 ],
       [-0.10991758],
       [-1.63933954],
       [-0.62946391],
       [ 1.77990465],
       [ 1.21865348],
       [-1.04202572],
       [ 0.07866904],
       [-0.12919526],
       [-1.12680126],
       [-0.53413491],
       [-0.95898833],
       [ 1.20943188],
       [ 1.61016272],
       [-0.01859783]])

In [14]:
#2 is a factorial of 16 so it is reshaped automatically,whenever you are giving negative number automatically it will decide the factorial of2
a4.reshape(8,-167890000000000)

array([[-0.82700022,  1.14365802],
       [-0.71306881,  0.19742828],
       [-0.18817338, -1.69836077],
       [ 0.62796614,  1.79629774],
       [ 0.05368645,  0.0575509 ],
       [-2.41344655,  0.21507751],
       [ 0.18133552,  0.4542044 ],
       [-0.75350661, -1.40400008]])

In [25]:
#in 3-d we have two 2*4 
a4.reshape(2,2,4)

array([[[-0.03817078, -0.88164863, -0.91861676,  1.37165402],
        [-1.26618054, -1.05781692, -1.43677868,  0.01056436]],

       [[-0.86520145, -1.53589603, -0.62951183,  1.05975024],
        [ 0.29793991, -0.4628386 ,  1.4336773 , -0.36773435]]])

In [30]:
a4.reshape(3,4,5)

ValueError: cannot reshape array of size 16 into shape (3,4,5)

In [19]:
a4

array([[-0.82700022,  1.14365802, -0.71306881,  0.19742828],
       [-0.18817338, -1.69836077,  0.62796614,  1.79629774],
       [ 0.05368645,  0.0575509 , -2.41344655,  0.21507751],
       [ 0.18133552,  0.4542044 , -0.75350661, -1.40400008]])

In [17]:
a7=a4.reshape(1,1,1,1,1,1,1,2,2,4)

In [18]:
a7.ndim

10

In [20]:
a7

array([[[[[[[[[[-0.82700022,  1.14365802, -0.71306881,
                 0.19742828],
               [-0.18817338, -1.69836077,  0.62796614,
                 1.79629774]],

              [[ 0.05368645,  0.0575509 , -2.41344655,
                 0.21507751],
               [ 0.18133552,  0.4542044 , -0.75350661,
                -1.40400008]]]]]]]]]])

In [33]:
a1

array(['4', '5', '6', '7', 'jaya', '34.565', 'True'], dtype='<U32')

In [28]:
a1[0]

'4'

In [34]:
a1[2:6]

array(['6', '7', 'jaya', '34.565'], dtype='<U32')

In [30]:
a1[2:6:2]

array(['6', 'jaya'], dtype='<U32')

In [31]:
a1[::-1]

array(['True', '34.565', 'jaya', '7', '6', '5', '4'], dtype='<U32')

In [35]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [63]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [34]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [35]:
a2[[0,1] , 1:]

array([[2, 3],
       [5, 6]])

In [71]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [27]:
a5 = np.random.randint(2,90 , (6,5))

In [39]:
a5

array([[71, 26, 65,  6, 23],
       [23, 15, 87, 85, 34],
       [ 9, 46, 70, 19, 63],
       [26, 75, 13, 24, 73],
       [74, 89, 52, 42, 12],
       [47, 47, 89, 77, 25]])

In [23]:
a5[a5>40]

array([52, 66, 43, 47, 58, 64, 76, 71, 85, 53, 53, 85, 67, 58, 50, 41])

In [28]:
a5

array([[68, 34, 54, 16, 26],
       [69, 66, 74, 29, 80],
       [42, 14, 16, 28, 33],
       [ 4, 27, 48, 65, 74],
       [64,  7, 86, 23,  3],
       [82, 80, 83, 57, 85]])

In [29]:
a5[0,1] = 100

In [30]:
a5

array([[ 68, 100,  54,  16,  26],
       [ 69,  66,  74,  29,  80],
       [ 42,  14,  16,  28,  33],
       [  4,  27,  48,  65,  74],
       [ 64,   7,  86,  23,   3],
       [ 82,  80,  83,  57,  85]])

In [33]:
a6 = np.random.randint(0,3 , (3,3))

In [31]:
a7 = np.random.randint(0,3 , (3,3))

In [34]:
a6

array([[0, 1, 2],
       [2, 1, 2],
       [0, 1, 1]])

In [35]:
a7



array([[0, 0, 2],
       [2, 1, 1],
       [1, 2, 0]])

In [36]:
#element wise multilication operation
a6*a7

array([[0, 0, 4],
       [4, 1, 2],
       [0, 2, 0]])

In [37]:
#matrix multiplication
a6@a7

array([[4, 5, 1],
       [4, 5, 5],
       [3, 3, 1]])

In [38]:
a6

array([[0, 1, 2],
       [2, 1, 2],
       [0, 1, 1]])

In [39]:
a6+100

array([[100, 101, 102],
       [102, 101, 102],
       [100, 101, 101]])

In [40]:
a6*2

array([[0, 2, 4],
       [4, 2, 4],
       [0, 2, 2]])

In [96]:
a6/0

C:\Users\win10\AppData\Local\Temp\ipykernel_22484\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\win10\AppData\Local\Temp\ipykernel_22484\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, inf, nan],
       [nan, inf, inf],
       [nan, nan, inf]])

In [41]:
a6

array([[0, 1, 2],
       [2, 1, 2],
       [0, 1, 1]])

In [42]:
#applying a6^3
a6**3


array([[0, 1, 8],
       [8, 1, 8],
       [0, 1, 1]], dtype=int32)

In [43]:
a8 = np.zeros((4,4))

In [44]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
a9  = np.ones((4,5))

In [104]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [49]:
#every row is added to array
a9 + (1,2,3,4,5)

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [107]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
#each and every row is added to array (broadcasting operation)
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [110]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
#coulmn wise broadcasting operation
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [114]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [116]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [51]:
a6.T

array([[0, 2, 0],
       [1, 1, 1],
       [2, 2, 1]])

In [119]:
a6

array([[0, 1, 0],
       [0, 1, 2],
       [0, 0, 1]])

In [52]:
a5

array([[ 68, 100,  54,  16,  26],
       [ 69,  66,  74,  29,  80],
       [ 42,  14,  16,  28,  33],
       [  4,  27,  48,  65,  74],
       [ 64,   7,  86,  23,   3],
       [ 82,  80,  83,  57,  85]])

In [121]:
np.sqrt(a5)

array([[ 6.40312424, 10.        ,  5.09901951,  8.83176087,  8.54400375],
       [ 7.81024968,  8.18535277,  5.47722558,  2.        ,  8.77496439],
       [ 4.47213595,  6.70820393,  9.32737905,  2.44948974,  9.        ],
       [ 2.44948974,  8.        ,  4.58257569,  6.4807407 ,  7.14142843],
       [ 7.81024968,  2.82842712,  5.29150262,  4.58257569,  7.41619849],
       [ 6.        ,  7.14142843,  7.87400787,  8.1240384 ,  4.79583152]])

In [122]:
np.exp(a5)

array([[6.39843494e+17, 2.68811714e+43, 1.95729609e+11, 7.49841700e+33,
        5.05239363e+31],
       [3.10429794e+26, 1.25236317e+29, 1.06864746e+13, 5.45981500e+01,
        2.75851345e+33],
       [4.85165195e+08, 3.49342711e+19, 6.07603023e+37, 4.03428793e+02,
        1.50609731e+35],
       [4.03428793e+02, 6.23514908e+27, 1.31881573e+09, 1.73927494e+18,
        1.40934908e+22],
       [3.10429794e+26, 2.98095799e+03, 1.44625706e+12, 1.31881573e+09,
        7.69478527e+23],
       [4.31123155e+15, 1.40934908e+22, 8.43835667e+26, 4.60718663e+28,
        9.74480345e+09]])

In [53]:
np.log10(a5)

array([[1.83250891, 2.        , 1.73239376, 1.20411998, 1.41497335],
       [1.83884909, 1.81954394, 1.86923172, 1.462398  , 1.90308999],
       [1.62324929, 1.14612804, 1.20411998, 1.44715803, 1.51851394],
       [0.60205999, 1.43136376, 1.68124124, 1.81291336, 1.86923172],
       [1.80617997, 0.84509804, 1.93449845, 1.36172784, 0.47712125],
       [1.91381385, 1.90308999, 1.91907809, 1.75587486, 1.92941893]])

In [55]:
list(range(0,10 ,2))

[0, 2, 4, 6, 8]

In [56]:
list(range(0,10 ,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [3]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [4]:
#num will define the total samples 
np.linspace(2,3,num=50,retstep=False, endpoint=False)

array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
       2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
       2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
       2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
       2.88, 2.9 , 2.92, 2.94, 2.96, 2.98])

In [136]:
np.logspace(2,4,num=4 , base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [12]:
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:

#plotly library
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns



In [5]:
!pip install cufflinks

In [10]:
cf.go_offline()

In [7]:
#100 rows , three columsn
df = pd.DataFrame(np.random.randn(100,3),columns=['A' , 'B' ,'C'])

In [8]:
df

A         B         C
0  -1.657389 -0.678908  0.605556
1   0.385092 -1.307148  0.187350
2   0.324166 -0.200614  0.859219
3  -1.285557  1.148258  1.938237
4  -0.858040 -0.857165  1.267334
..       ...       ...       ...
95 -1.177619  0.084017  0.412923
96  0.822085 -1.023514 -0.156380
97 -1.136586  0.994629  0.366140
98 -0.429966  0.396263 -0.130509
99  0.202813  1.442025  1.664399

[100 rows x 3 columns]

In [11]:

df.iplot()

In [13]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1))) 

In [149]:
df1

0
0   38
1   82
2   61
3   12
4   92
..  ..
95  74
96  81
97  69
98  36
99  27

[100 rows x 1 columns]

In [14]:

df1.iplot()#we can know hpw it is varying

In [22]:
df1

0
0   79
1   46
2   41
3   99
4   11
..  ..
95  69
96  42
97  70
98  79
99  59

[100 rows x 1 columns]

In [23]:
df

A         B         C
0   1.074297 -1.001775  0.791877
1  -1.531421  0.070365  1.089598
2   0.720360 -0.538438 -0.929142
3   0.949600 -0.702064  1.331233
4  -1.288218 -0.476923  1.138459
..       ...       ...       ...
95 -0.750347 -0.116253  1.117707
96  0.214894 -1.025801 -0.004067
97 -0.354864 -0.103601 -2.631051
98  0.416208  0.547720 -0.449073
99  0.017847 -1.363888  0.333935

[100 rows x 3 columns]

In [16]:
df.iplot()

In [15]:
df.iplot(x = 'A' , y = 'B',mode = 'markers')

In [17]:
df2 = sns.load_dataset('titanic')

In [26]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [18]:
df2.iplot(x = 'age' , y ='fare',mode = 'markers' )

In [28]:
df2.iplot(x = 'age' , y ='pclass',mode = 'markers' )

In [29]:
df2.iplot(x = 'fare' , y ='pclass',mode = 'markers' )

In [167]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [31]:
df2.iplot(kind = 'bar' , x = 'sex' , y = 'survived')